Add files via upload
Ok, so I finished and was trying to push my stuff and got {  ! [rejected]        master -> master (non-fast-forward)
error: failed to push some refs to 'https://github.com/DelroyMyrie/python-challenge.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details. } so i couldn't get past that point to then link the repository to homework